name: test

on:
  push:
  pull_request:

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'jetbrains'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: test
        run: ./gradlew test
      
      - name: publish report 
        run: |
          cd app/build/reports/tests/test
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
          echo '{
            "name": "@xiaochuan-dev/java-test",
            "version": "0.0.1",
            "publishConfig": {
              "access": "public",
              "registry": "https://registry.npmjs.org/"
            }
          }' > package.json
          npm publish