name: test

on:
  push:
  pull_request:

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'jetbrains'

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org/'

      - name: node version
        run: node --version

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: test
        run: ./gradlew test
      
      - name: publish report 
        run: |
          cd app/build/reports/tests/test
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc

          curl -O https://unpkg.com/@xiaochuan-dev/java-test-script@0.0.2/index.js

          node index.js > out.json

          mv out.json package.json

          cat package.json

          npm publish